# Generated by Django 4.1.4 on 2023-02-12 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentoanual',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='principal.docente', verbose_name='Docente'),
        ),
    ]
