# Generated by Django 4.1.4 on 2023-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_planodeaula_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discente',
            name='turma',
        ),
        migrations.AddField(
            model_name='discente',
            name='turma',
            field=models.ManyToManyField(blank=True, null=True, related_name='alunos', to='principal.turma', verbose_name='Turma do aluno'),
        ),
    ]
