# Generated by Django 4.1.4 on 2023-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_discente_turma_discente_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='turma',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='principal.turma', verbose_name='Turma do aluno'),
        ),
    ]
