# Generated by Django 4.1.4 on 2023-03-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_discente_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='discente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='vicediretor',
            name='data_de_nascimento',
            field=models.DateField(blank=True, default='01/01/2000', max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
